### PR TITLE
Set date format by reading dates from the ledger file

### PR DESCRIPTION
**Pull request by justinjk007**
I am only looking for date format like this `yyyy/MM/dd` if that doesn't exist I fall back to `yyyy-MM-dd`. Hopefully these formats are enough for now.

### CODE REVIEW

**Comment by bradyt** [comment]
Thank you @justinjk007,

This looks good. I haven't had a workflow to hack on this app in a few months, so I need to look at some things when I get enough time, but I hope to give this a complete review soon.

Note, I haven't added widget tests, nor any sort of CI testing, or much automation to existing tests, so I will have to tread carefully.

I'd also like to improve how easy it is to have two easily distinguishable apps installed, one for using, and one for testing.

The commit as is, might be the best thing to commit to master, so that as it stands, it will be easy to read and catch issues if any arise. But in the long run, I may, after this commit stands the test of time, end up refactoring, so instead of being in FileModel, you can test the existing `chunks`, and potentially update the FormatModel. I'm sure I'm missing something there, but that would be exactly why I want to take a longer look at this.

**Comment by bradyt** [comment]
@justinjk007, why do you have these lines in your commit?

```diff
+          caseSensitive: false,
+          multiLine: false,
```

**Comment by justinjk007** [comment]
It was in the example when I tried to lookup syntax for regex matching, we don't need them I think. I will remove those add the regex suggestion .

**Comment by justinjk007** [comment]
>Note, I haven't added widget tests, nor any sort of CI testing, or much automation to existing tests, so I will have to tread carefully.

I have setup CodeMagic CI for one of my before that was pretty simple. I am guilty of never writing widget tests too. I do want to learn thou, I will chip in some as we go along.

**Comment by bradyt** [comment]
Hmm, maybe we need `multiLine: true,`.

From https://api.dart.dev/stable/2.7.0/dart-core/RegExp/RegExp.html:

> If `multiLine` is enabled, then `^` and `$` will match the beginning and end of a _line_, in addition to matching beginning and end of input, respectively.

**Comment by justinjk007** [comment]
But we just need to match one line anyways? By adding ^ aren't we expecting
the beginning of our input to be a date anyways? It might be useful if
someone need to get all the matches, for our usecase we only need to match
once.

**Comment by bradyt** [comment]
You can try the following at https://dartpad.dev/.

```dart
void main() {
  print(RegExp(r'^blah').hasMatch('''
first line
blah'''));
  // false
  print(RegExp(r'^blah', multiLine: true).hasMatch('''
first line
blah'''));
  // true
}
```

**Comment by bradyt** [comment]
@justinjk007 I think the `r'^[0-9]+/'` won't work without `mulitLine: true`, with the following file example.

```
;; a comment
2020/01/01 an example
  a    5.00 EUR
  b
```

I think the only way the current code would work, is if the first line of the entire file had a transaction with a date with forward slashes.

I think you'll see that `multiLine: true` fixes this.

**Comment by bradyt** [comment]
This all looks good. Can we rebase as one commit on master?

**Comment by justinjk007** [comment]
Squashed all the commits into one.

**Comment by bradyt** [comment]
Great, I've rebased to master and pushed. Apparently Github is broken, so it does know this "pull request" has been "merged". Closing manually.

**Pull request closed without merging**
